export * from './frame-page'
export * from './product-details'
export * from './main-page'
export * from './login-page'
export * from './register-page'
export* from './register-result'
export * from './search-page'
export * from './shoping-cart'
export * from './checkout-page'
export * from './my-account-page'